name = "SelfConsistentLogisticNoise"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0-DEV"
authors = ["Isaia Nisoli"]

[deps]
BallArithmetic = "77e4f72b-b5a4-4fb0-ac2a-dcc32095a072"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BallArithmetic = "0.1"
CSV = "0.10"
DataFrames = "1"
FFTW = "1"
IntervalArithmetic = "0.20, 0.21, 0.22"
JLD2 = "0.4, 0.5, 0.6"
Plots = "1.41.4"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
