name = "SelfConsistentLogisticNoise"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Isaia Nisoli"]
version = "0.1.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataFrames = "1"
CSV = "0.10"
FFTW = "1"
JLD2 = "0.4"
julia = "1.9"
